global proc shelf_Fireflies () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Open a scene and set the desired production context" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Context" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Set Context" 
        -overlayLabelColor 0.772358 0.772358 0.772358 
        -overlayLabelBackColor 0 0 0 0.4 
        -image "C:/Fireflies/Fireflies_BIN/fireflies/logos/set_context.png" 
        -image1 "C:/Fireflies/Fireflies_BIN/fireflies/logos/set_context.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from fireflies.context import context_window\n\ncontext = context_window.context_window()\ncontext.show()\n" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Create a production asset" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Create_Asset" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Create Asset" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "C:/Fireflies/Fireflies_BIN/fireflies/logos/asset_creator.png" 
        -image1 "C:/Fireflies/Fireflies_BIN/fireflies/logos/asset_creator.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from fireflies.maya import create_usd_asset\n\nx = create_usd_asset.create_usd_asset_window()\nx.show()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Import a production related asset" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "prod_asset" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Prod Asset" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "C:/Fireflies/Fireflies_BIN/fireflies/logos/asset_importer.png" 
        -image1 "C:/Fireflies/Fireflies_BIN/fireflies/logos/asset_importer.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from PySide2 import QtWidgets\n\nfrom fireflies.fireflies_utils.usd import usd_asset_importer_hou\n\nwin = usd_asset_importer_hou.importer_window()\n\nif win.exec_() == QtWidgets.QDialog.Accepted:\n\tpass\n" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Set scene frame range from the kitsu / server data" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "set_frange_kt" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Kitsu Frame Range" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "C:/Fireflies/Fireflies_BIN/fireflies/logos/kt_frange.png" 
        -image1 "C:/Fireflies/Fireflies_BIN/fireflies/logos/kt_frange.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from fireflies.context import prod_tracker\n\nimport maya.cmds as cmds\n\nCONTEXT = prod_tracker.manage_context()\n\ncurrent_path = cmds.file(q=True, sn=True).replace('/', '\\\\')\nCONTEXT.set_scene_range(current_path)" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
